### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by reiroldan** [martinrue/Tinyweb#10]
Hi, 

There are a few places where you should take into consideration the current locale in order to get the correct value for  parameters. For example, the current unit tests fail at 3 points when using double or decimal types with a system where the decimal separator is a "," (coma) instead of a "." (period).

The following tests:
ParseAcceptHeader_MultipleTypesAndPriorities_FindsCorrectTypesAndPriorities
ParseAcceptHeader_SingleTypeAndPriority_FindsCorrectTypeAndPriority
HttpPOST_WithAllParameterSources_CallsHandlerPostMethodAndReturnsCorrectData

Are the ones that fail immediately, these can be fixed quite easily by replacing:

method: Extensions.ParseAcceptHeader 

From:
  mimeTypes.Add(preferenceParts.ElementAt(0), Convert.ToDouble(preferenceParts.ElementAt(1).Substring(2)));
To:
  mimeTypes.Add(preferenceParts.ElementAt(0), Convert.ToDouble(preferenceParts.ElementAt(1).Substring(2), CultureInfo.InvariantCulture));

And

method: ArgumentBuilder.changeType

From: 
  return Convert.ChangeType(value, conversionType);
To:
  return Convert.ChangeType(value, conversionType, CultureInfo.InvariantCulture);

Nice framework over all. Good work :)

**Comment by martinrue** [comment]
Many thanks for finding this, I never even thought to test the framework with a non 'en' culture.

I've spent some time looking into the issue and there are two separate things happening:
1. As you mentioned, the tests for parsing the accept header were using the current culture and hence failing in other cultures. Your suggestion of using `CultureInfo.InvariantCulture` solved that perfectly, as the accept header is culture agnostic as per http://stackoverflow.com/questions/8912082/can-http-headers-be-localized/8912149#8912149 
2. The second issue is the `Convert.ChangeType` in `ArgumentBuilder`. If I was to use an invariant culture here, it would prevent the model binder from using the correct specific culture as denoted by the `Accept-Language` HTTP header. As it happens, ASP.NET can solve this via the `web.config` by automatically setting the current thread culture based on the incoming request:

```
<system.web>
    <globalization enableClientBasedCulture="true" uiCulture="auto" culture="auto"></globalization>
</system.web>
```

Allowing for `en-GB` requests with `0.5` to work, but also `de-DE` requests with `0,5`.

I think this is a good solution for times when you need to support incoming data from potentially different cultures. Please re-open the issue if I've missed something, though :)

Thanks very much for identifying and raising the issue.

**Comment by reiroldan** [comment]
Thats perfect and works like a charm, thank you.
