### ISSUE TITLE
Include section on modifying web.config for running on IIS

### ISSUE THREAD

**Issue by matlarsen** [martinrue/Tinyweb#11]
Hey team

Loving your code

Just thought it might be helpful to new users to include putting this in a web.config to get people started with tinyweb on IIS
'''
<system.web>
    <compilation debug="true" targetFramework="4.0" />
    <httpHandlers>
      <add verb="*" type="tinyweb.framework.HttpHandler" path="*" />
    </httpHandlers>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <add name="Tinyweb" verb="*" type="tinyweb.framework.HttpHandler" path="*" />
    </handlers>
  </system.webServer>
'''

**Comment by martinrue** [comment]
Hey Matthew,

Are you referring to IIS 7 or greater here, or an earlier version? 

You shouldn't need to add anything additional to the standard web.config generated with a Project -> New -> Empty ASP.NET Web Application as far as I knew?

**Comment by matlarsen** [comment]
Hey,

Yeah IIS 7 and up. I had to add some sections to set the routing - but I messed up my markdown in the original message, here we are again

```
<system.web>
    <compilation debug="true" targetFramework="4.0" />
    <httpHandlers>
      <add verb="*" type="tinyweb.framework.HttpHandler" path="*" />
    </httpHandlers>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <add name="Tinyweb" verb="*" type="tinyweb.framework.HttpHandler" path="*" />
    </handlers>
  </system.webServer>
```

**Comment by martinrue** [comment]
Tinyweb HTTP handlers are auto discovered and registered, so you shouldn't need the handlers bit of the web.config. You also shouldn't need the validation stuff. Try using the following:

```
<?xml version="1.0"?>

<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.0" />
  </system.web>

  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
  </system.webServer>
</configuration>
```

If that works for you, I'll add this to the readme as per your original suggestion :)

Mart

**Comment by matlarsen** [comment]
yep yep! I thought it shouldn't, but I found I had to add em. Cheers guys
